### ISSUE TITLE
Install Chrome extension from web store

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#111]
## User Story

As a user
I want to be able to view and install the vega browser wallet for Chrome from the Chrome web store
So that I can try out the shiny new Vega browser wallet early and help the team improve it before launch

## Acceptance Criteria

I can find the vega wallet browser extension for Chrome in the Chrome web store
I can install the vega wallet browser extension to my Chrome browser
When I have installed the extension I can see a 'Vega' icon in my browsers extension list/bar 

## Tasks

- [ ] Sketch and define content
- [ ] Review with stakeholders
- [ ] Visual Design
- [ ] Implement
- [ ] QA Test
- [ ] Release

## Notes

Chrome has a review process (and manual process for the first release), but sure what that is yet

For initial release only able to have a small group of users
Can have a small approval group so could add all devs or similar

**Comment by pennyandrews** [comment]
@dalebennett1992 we believe this is already done so would be great if you can just test and verify and ensure you are happy that there is suitable test coverage for it and it's covered in the specs etc. 🙏
