### ISSUE TITLE
Wallet throws Internal error when calling 'admin.lock' on an already locked wallet

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/vegawallet-browser#221]
## Description

I am trying to configure a consistent state for my tests across chrome and firefox for the 'remember where I am in onboarding' set of AC. Chrome and Firefox behaviour differs slightly when it comes to redirecting the user to the locked wallet page. Because of this I am trying to lock the wallet by default for the sake of these tests so the test can follow a consistent set of steps on each browser. When doing this we found that calling `admin.lock` on an already locked wallet throws an Internal error as shown below:
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/3743f6b2-561f-495b-9c30-f833acb16d30)
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/c9b3c539-6c28-425a-8ae2-5c5d5930c4d7)

## Steps to Reproduce

1. Open the extension in firefox or chrome
2. Follow the onboarding steps to create wallet and keys
3. Click 'Settings' in the nav panel
4. Click 'Lock' to lock the wallet
5. Open the dev console in the context of the extension
6. run the following:
    `const resp = await client.request('admin.lock', null)`
7. Observe 'Uncaught Error: Internal error' appears

## Expected behavior

Would expect this case to be handled instead of throwing an Internal error. Would be nice to receive a 'null' response regardless even if the wallet is already in a locked state

- OS: WSL Ubunty 22.04
- Browse Chrome

**Comment by dexturr** [comment]
No longer present, likely fixed during the refactor of the ecrypted storage a while ago
