### ISSUE TITLE
Visual feedback for a successful connection

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#250]
## Chore

Add user feedback after they have selected to connect in a connection request. 

## Acceptance Criteria

- [ ] There is a visual way to understand that a connection has been successful

## Reference 

<img width="1102" alt="Screenshot 2023-06-01 at 08 05 27" src="https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/627afe3d-a4ef-40fe-95fe-caf53a677999">

**Comment by pennyandrews** [comment]
@dalebennett1992 we believe this is already done so would be great if you can just test and verify and ensure you are happy that there is suitable test coverage for it and it's covered in the specs etc. 🙏
