### ISSUE TITLE
Support new transaction types coming from core

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#282]
## Chore

The new core features introduce new transaction types that we need to ensure are supported in the browser wallet ready for Deployment 1.

- Successor Markets - new transaction type
- Governance Transfers - new transaction types
- Stop Orders - new transaction types
- Iceberg Orders  - new transaction types

## Tasks

- [ ] 
- [ ] 
- [ ]

**Comment by emilbayes** [comment]
These will be automatically supported once the protos are in an official release 👍

**Comment by pennyandrews** [comment]
Yep, I know that's the theory.... but this is a placeholder ticket to remind us that we will need to check and validate this when we get close to the release :)
