### ISSUE TITLE
Whole team swarm testing

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#340]
Once everything else in the sprint is done we want to swarm test it whereby every team member goes through our full journey in an attempt to find bugs/issues etc. 

As much as possible we want to consider different routes through the features, different browsers, connecting with different apps etc. 

Once we are done we will share with the wider Vega team and invite them to do the same before we formally launch the release with the community

**Comment by ckpringle** [comment]
@JonRay15 to set up a silent call to make this happen

**Comment by JonRay15** [comment]
We dont appear to be doing this...... shall we just accept defeat?
