### ISSUE TITLE
Password no longer recognised after having multiple extensions installed

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#343]
## Description

When I have connected before to the sample dapp, and had both mainnet and fairground browser extensions installed but subsequently removed one... when I need to enter my password for whatever reason in one extension, my password is no longer recognised, followed by receiving an internal error. See attached screencast. 

May be related to #333 

## Steps to Reproduce

1. Go to https://vegaprotocol.github.io/vegawallet-browser/
2. Click on connect
3. Then disconnect
4. Quit the browser
5. Reopen the browser and go to connect again 
6. Try entering your password (you'll see red copy "incorrect passphrase"
7. Close the wallet and reopen it (you'll see internal error)

## Screenshots/casts

https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/b6662bd1-983a-4ab2-a0cf-e097463c853b

## Device details

- OS: MacOS 
- Browser Chrome 114.0.5735.198

**Comment by dalebennett1992** [comment]
this looks to have been resolved after retesting.
