### ISSUE TITLE
Password being requested too many times

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#374]
## Description

* Work out what the existing behaviour is for password / login requests i.e. is it time based 
* Work out how to increase the time, ideally to the point that it's only requested if I quit the browser 
* List the conditions i.e. some browsers might have different defaults

## Background
_It should remember the password for login sessions if they don't close the browser or lock wallet (Current settings seem like after a fairly short amount of time the wallet will automatically lock)_

## Expected behavior

A clear and concise description of what you expected to happen (we can use these to build out our A/Cs, verify the fix and increase our test coverage)

- [ ] I can 
- [ ] I can
- [ ] I can

## Logs

If applicable, please provide the output of both
the DevTools console from the dApp used, the error page from the
`about:addons` (FF) / `chrome://extensions/` (Chromium) page and relevant logs
from the background script and popup.
[See this guide for Chromium](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/)
or [this guide for Firefox](https://extensionworkshop.com/documentation/develop/debugging/)

## Screenshots/casts

If applicable, add screenshots/casts to help us understand the problem.

## Device details

- OS: [e.g. macOS]
- Browser [e.g. Firefox, Chrome, Brave]
- Version [e.g. 109]

**Comment by emilbayes** [comment]
#377 may be a potential fix for this
