### ISSUE TITLE
SPIKE: How to verify if a dapp can be trusted

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#422]
## The Spike

I want to be able to verify if this dapp (Console in the first instance) can be trusted

## Questions we need to answer

- [ ] Is there a way to check if the IPFS hash I'm seeing is for the right release, via github maybe?
- [ ] Can we automate this and signal some kind of 'trusted' status in the UI?
- [ ] What else?

## Tasks

- [ ] 
- [ ]
- [ ]

**Comment by JonRay15** [comment]
Dont need anymore due to vegaptorocol.eth
