### ISSUE TITLE
Support for mainnet mirror environment

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#442]
## Spike

We need to understand the work required to support the mainnet mirror environment, aside from https://github.com/vegaprotocol/frontend-monorepo/issues/4346

Questions to answer
- Do we enable network switching for it as the versions should be on same code version 
- Do we have another separate wallet release
- Relates to whether / when we "do" support multiple networks (in roadmap but further down https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764549641664244&cot=14)

## Tasks

- [ ] 
- [ ] 
- [ ]

**Comment by JonRay15** [comment]
Will be covered by multi-network support.
