### ISSUE TITLE
Spike: How to avoid a new connection request every time Console is updatedSPIKE: 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#452]
E.g. There could be a way to opt in to automatically connect every time console is updated

## The Spike

Description of what we trying to achieve (a user story would be ideal) and why we need a spike i.e. to establish what’s possible / how we can achieve it based on what functionality / data in core  

## Questions we need to answer

- [ ] 
- [ ] 

## Tasks

- [ ] 
- [ ]
- [ ]

**Comment by JonRay15** [comment]
With the new .eth.limo domain this is no longer a problem
