### ISSUE TITLE
Update/rename wallet

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegawallet-browser#464]
## Story

**As a** user
**I want** to rename my wallet 
**So that** I can easily tell which wallet I'm using 

## Acceptance Criteria

- [ ] There is a way to rename a wallet 
- [ ] The new name of a wallet is shared with connected dapps
- [ ] I can see the new name in the wallet UI
- [ ] There is a way to set the name of a wallet when I initially create/import it

**Comment by JonRay15** [comment]
I'm just going to add these ACs to the multi-wallet ticket and close this.
