### ISSUE TITLE
Connection list showing oldest connection first. Should be newest first

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/vegawallet-browser#485]
## Description

If I connect to browser wallet via multiple dapps, I see the oldest connection at the top of the connection list. I would expect to see the most recent connection at the top

## Steps to Reproduce

1. Get the browser wallet extension and on board
2. Open https://vegaprotocol.github.io/vegawallet-browser/ and connect to the wallet
3. approve the connection in the wallet
4. Go to arsenal.com and in the console execute vega.connectWallet()
5. approve the connection in the wallet
6. Click 'Connections' in the browser wallet navigation panel
7. observe that https://vegaprotocol.github.io/vegawallet-browser/  is shown first in the connections list, even though my connection to arsenal.com was more recent

## Expected behavior
Most recent displayed first.

## Screenshots/casts

![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/6a3312c1-7780-45cb-bcf3-f4702d4bbd8e)

## Device details

- Browser wallet 0.7.0 chrome

**Comment by emilbayes** [comment]
Backend API sorts by most recently used first. This is covered in this tests: 

https://github.com/vegaprotocol/vegawallet-browser/blob/0d90faafe40c36df89e6217eadc6bc5cdb745149/web-extension/test/connections.spec.js#L190-L194
