### ISSUE TITLE
Update Team TX is failing

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#697]
## Chore

Tried to update a team 

no bueno

<img width="616" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/7f8dd1c1-2dd7-4166-8fea-1c5f6bfa91ba">

## Tasks

- [ ] Fix it please
- [ ] 
- [ ]

**Comment by dexturr** [comment]
Closing as not a bug, the transaction data being sent was incorrect
