### ISSUE TITLE
UX feedback on the wallet popup when wallet locked in autosign mode

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#785]
## Chore

Current behaviour:

1. Wallet locked wont autosign TXs (expected)
2. Once you unlock it you still get a popup for aproval even though you now unlocked it
3. In that state you dont get the info that its in autosign mode

## Acceptance Criteria

- [ ] All Txs queued up while locked should be displayed
- [ ] There should be a "send it all" button when you have a queue of TXs
- [ ] It should be clear if you are moving back to autosigning mode when you send it all

**Comment by barnabee** [comment]
I don't think this quite captures it. The feedback and observations from my interactions with users were:

1. It is surprising that the wallet pops up, the user is not expecting it, and it doesn’t tell them why it’s popped up. As far as they’re concerned they are never expecting it to do that when trading.
2. It is not clear to the user when the wallet pops up that the transaction won’t be sent unless they unlock it AND take an action. They told it to automatically send transactions without showing a UI, so why would they need to unlock the UI? The user perhaps no longer has a mental connection between sending a transaction and the wallet [UI} at all, and believes the app is allowed to just get on with sending them.
3. Once it’s unlocked, there is no context telling the user why they are being asked to sign this transaction, also hard to find when it was sent as this info is at the bottom (I saw a user convinced the data wasn’t there as they didn’t scroll past the JSON.
4. There’s also nothing reassuring the user on the request that auto-sign is still enabled and they are just being asked to confirm the they want the transaction(s) that were done while locked.
